"use client";
import { useEffect, useState } from "react";
import { onValue, ref } from "firebase/database";
import { httpsCallable } from "firebase/functions";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { defaultSettings, settingsSchema } from "@miner/shared";
import type { z } from "zod";
import { PageHeading } from "@/components/page-heading";
import { useAuth } from "@/hooks/use-auth";
import { database, functions } from "@/lib/firebase";
const formSchema = settingsSchema.omit({ ownerId: true, createdAt: true, updatedAt: true }); type FormInput = z.input<typeof formSchema>; type FormData = z.output<typeof formSchema>;
export default function SettingsPage() { const { user } = useAuth(); const [message, setMessage] = useState(""); const { register, handleSubmit, reset, formState: { errors, isSubmitting } } = useForm<FormInput, unknown, FormData>({ resolver: zodResolver(formSchema), defaultValues: defaultSettings }); useEffect(() => { if (!user) return; return onValue(ref(database, 'settings/' + user.uid), (snapshot) => { if (snapshot.exists()) reset(snapshot.val() as FormData); }); }, [user, reset]); const submit = async (values: FormData) => { setMessage(""); await httpsCallable(functions, "updateSettings")(values); setMessage("Settings saved by the trusted backend."); }; const fields: { key: "electricityPriceINRPerKWh" | "telemetryIntervalSeconds" | "backendTimeoutSeconds" | "maxSessionDurationMinutes" | "maxGpuTemperatureC" | "maxCpuTemperatureC" | "minBatteryPercent"; label: string; step?: string }[] = [{ key: "electricityPriceINRPerKWh", label: "Electricity price (INR/kWh)", step: "0.01" }, { key: "telemetryIntervalSeconds", label: "Telemetry interval (seconds)" }, { key: "backendTimeoutSeconds", label: "Backend timeout (seconds)" }, { key: "maxSessionDurationMinutes", label: "Maximum session (minutes)" }, { key: "maxGpuTemperatureC", label: "Maximum GPU temperature (°C)" }, { key: "maxCpuTemperatureC", label: "Maximum CPU temperature (°C)" }, { key: "minBatteryPercent", label: "Minimum battery (%)" }]; return <><PageHeading title="Settings" description="Validated safety defaults; hardware enforcement begins in later phases."/><form className="panel max-w-3xl p-6" onSubmit={handleSubmit(submit)}><div className="grid gap-4 md:grid-cols-2"><label>Timezone<input className="field mt-1" {...register("timezone")}/></label>{fields.map(({ key, label, step }) => <label key={key}>{label}<input className="field mt-1" type="number" step={step ?? "1"} {...register(key, { valueAsNumber: true })}/>{errors[key] && <small className="text-red-500">Invalid value</small>}</label>)}<label className="flex items-center gap-3 pt-7"><input type="checkbox" {...register("chargingRequired")}/> Charging required</label></div><div className="mt-6 flex items-center gap-4"><button className="button" disabled={isSubmitting}>{isSubmitting ? "Saving…" : "Save settings"}</button>{message && <span className="muted">{message}</span>}</div></form></>; }

