"use client";
import { useState } from "react";
import { httpsCallable } from "firebase/functions";
import { PageHeading } from "@/components/page-heading";
import { StatusPill } from "@/components/status-pill";
import { effectiveAvailability, useDevices } from "@/hooks/use-devices";
import { functions } from "@/lib/firebase";
function shownTime(value: unknown): string { if (!value) return "Not available"; if (typeof value === "object" && value !== null && "toDate" in value) return (value as { toDate(): Date }).toDate().toLocaleString(); return new Date(String(value)).toLocaleString(); }
export default function DevicesPage() { const { devices, loading, error } = useDevices(); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const addDevelopmentDevice = async () => { setBusy(true); setMessage(""); try { await httpsCallable(functions, "createDevice")({ deviceName: "Development device", deviceType: "WINDOWS" }); setMessage("Development-only device created."); } catch { setMessage("Development creation is disabled. Enable it only in the local emulator."); } finally { setBusy(false); } }; return <><PageHeading title="Devices" description="Registered controllers and their latest reported state."/><div className="mb-5 flex flex-wrap items-center gap-3"><button className="button" onClick={addDevelopmentDevice} disabled={busy}>{busy ? "Adding…" : "Add Device"}</button><span className="muted text-sm">DEVELOPMENT ONLY · emulator-gated</span></div>{message && <p className="muted">{message}</p>}{error && <p role="alert" className="text-red-500">{error}</p>}<section className="panel overflow-hidden">{loading ? <p className="p-6 muted">Loading devices…</p> : devices.length === 0 ? <div className="p-8 text-center"><h2>No devices yet</h2><p className="muted">Real pairing arrives in Phase 3. The local emulator can create an authorized development record.</p></div> : <div className="overflow-x-auto"><table className="w-full border-collapse text-left"><thead style={{ background: "var(--panel-2)" }}><tr>{["Device", "Type", "Status", "State", "Last seen", "Software"].map((h) => <th className="p-4 text-sm" key={h}>{h}</th>)}</tr></thead><tbody>{devices.map((d) => <tr key={d.deviceId} className="border-t" style={{ borderColor: "var(--line)" }}><td className="p-4 font-semibold">{d.deviceName}</td><td className="p-4">{d.deviceType}</td><td className="p-4"><StatusPill label={effectiveAvailability(d)}/></td><td className="p-4"><StatusPill label={d.operationalState}/></td><td className="p-4">{shownTime(d.lastSeen)}</td><td className="p-4">{d.softwareVersion || "Not available"}</td></tr>)}</tbody></table></div>}</section></>; }

